### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by will-thrive** [friyiajr/BluetoothLowEnergySample#3] opened 2023-01-01 11:40 UTC
Hi Dan

I am seeing the following warning messages. Do you get them too?  Do you know of a proper fix for this issue?

 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method. 

I am using react@18.1.0 and react-native@0.70.2 on a Mac to create an Android app (Android 13)

Thanks.

**Comment by friyiajr** [comment] 2023-01-01 12:09
Hey, unfortunately this needs to be fixed upstream at the Library Level. I see this problem as well when I set up the library in new projects. You have to go into the Android native code and create those methods for the warning to go away as you can see [here](https://stackoverflow.com/a/69650217). The issue is open on the react-native-ble-plx side as you can see here https://github.com/dotintent/react-native-ble-plx/issues/988. Hopefully they can get to it eventually. Closing for now since there isn't much I can do on my end other then add code to ignore the error. I know this issue says Expo but its relevant to all React-Native versions

**Closed as completed by friyiajr** 2023-01-01 12:09 UTC

**Comment by will-thrive** [comment] 2023-01-03 08:36
Ok. Thanks for the info.
